services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: FHSSweb1!
      POSTGRES_DB: starter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - dev_network

  # minio:
  #   image: minio/minio:RELEASE.2025-04-22T22-12-26Z
  #   container_name: minio
  #   restart: unless-stopped
  #   environment:
  #     MINIO_ROOT_USER: admin
  #     MINIO_ROOT_PASSWORD: FHSSweb1!
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio_data:/data
  #   ports:
  #     - "9000:9000" # S3 API
  #     - "9001:9001" # Web Console
  #   networks:
  #     - dev_network

volumes:
  postgres_data:
  # minio_data: # Uncomment if using minio

networks:
  dev_network:
    driver: bridge
